apiVersion: v2
description: Helm chart formifos-gazelle infrastructure services
name: gazelle-infra
version: 0.1.0
appVersion: "kafka: 19.0.2; console: 0.6.6; mongodb: 13.3.1; mongo-express: 1.0.2; elasticsearch:19.9.2; redis: 17.11.6"
home: https://github.com/openMF/mifos-gazelle
#icon: 
sources:
- https://github.com/openMF/mifos-gazelle
maintainers:
- name: Tom Daly 
  email: tdaly61@gmail.com
dependencies:
## kafka 
- name: kafka
  alias: kafka
  condition: kafka.enabled
  repository: https://charts.bitnami.com/bitnami
  tags:
  - gazelle
  - dependency
  - kafka
  version: 18.5.0
## redpanda kafka console 
- name: console
  alias: redpanda-console
  condition: console.enabled
  repository: https://charts.redpanda.com
  tags:
  - gazelle
  - dependency
  - kafka
  - redpanda
  version: 0.6.6
## MongoDB
- name: mongodb
  alias: mongodb
  condition: mongodb.enabled
  repository: https://groundhog2k.github.io/helm-charts/
  tags:
  - gazelle
  - dependency
  - mongodb
  version: 0.6.0
## Mongo-express
- name: mongo-express
  alias: mongo-express
  condition: mongo-express.enabled
  repository: https://cowboysysop.github.io/charts/
  tags:
  - gazelle
  - dependency
  - mongodb
  version: 6.5.2
## redis 
- name: redis
  alias: redis 
  condition: redis.enabled
  repository: https://charts.bitnami.com/bitnami
  tags:
  - gazelle
  - dependency
  - mongodb
  version: 17.11.6
## Elastic Search Kibana 
- name: elasticsearch
  alias: elasticsearch
  condition: elasticsearch.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - mojaloop
  - dependency
  - vNext
  - elasticsearch
  version: 19.13.5
## MySQL
- name: mysql
  alias: mysql
  condition: mysql.enabled
  repository: https://charts.bitnami.com/bitnami
  tags:
  - gazelle
  - dependency
  - mysql
  version: 9.4.5
